# -*- coding: utf-8 -*-
"""Github-Demo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11NvHxcn7wHcWrY5B48_ho2XJoYNvOe8G
"""

#Use this code for the git-demo
#write your name

name = "Sajal"

name_s = "Sabelo"
print (name)
print(name_s)
